name:                timeout
version:             1.0.0.0
github:              "philwade/timeout"
license:             BSD3
author:              "Phil Wade"
maintainer:          "phil@philwade.org"
copyright:           "2018 Phil Wade"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/philwade/timeout#readme>

dependencies:
- base >= 4.7 && < 5
- hspec
- regex-posix
- unix
- strict
- ansi-terminal

library:
  source-dirs: src

executables:
  timeout:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - timeout

tests:
  timeout-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - timeout
